Energy system and Zero Copy example
solana-playground/solana-playground pull request #127
Opened 2023-04-14 13:28 UTC by Woody4618

Two new examples: 
Zero copy consists of three tests showing stack frame size limit, how to create accounts bigger than 10Kb and how to use zero copy serialization. 

Lumberjack shows how to use unix time stamps and how to create an energy mechanic for a game.

2023-04-16 10:19 UTC, acheroncrypto requested changes
Hey, thank you for the tutorials. Please check the review comments. Main part is that the code in markdown files should specify the correct language and also the code should be formatted.

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/about.md
> +Energy systems are very popular in traditional casual games. It means having an energy value which refills over time. And the energy is used to do certain actions in the game. If you have no prior So
We can add link to the Tiny Adventure Tutorial.

```suggestion
Energy systems are very popular in traditional casual games. It means having an energy value which refills over time. And the energy is used to do certain actions in the game. If you have no prior Solana Knowledge please start with the [Tiny Adventure Tutorial](/tutorials/tiny-adventure).
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/files/anchor.test.ts.raw
Can we remove this file if it's not going to be used?

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/files/client.ts.raw
What do you think about removing pre-written code since the same code already exists in the markdown files?

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/files/lib.rs
What do you think about removing pre-written code since the same code already exists in the markdown files?

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/pages/3.md
> +  .catch(async (error) => {
This is an anti-pattern, please use `try { ... } catch { ... }` sytnax instead of awaiting a `Promise.catch`

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/pages/3.md
> +      .signers([pg.wallet.keypair])
`pg.wallet.keypair` is already the signer when sending transactions.

```suggestion
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/pages/3.md
> +  .signers([pg.wallet.keypair])
`pg.wallet.keypair` is already the signer when sending transactions.

```suggestion
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/pages/3.md
> +```js
We can specify `bash` here instead of `js`.

```suggestion
```sh
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/TinyAdventureTwo/pages/3.md
> +  .signers([pg.wallet.keypair])
`pg.wallet.keypair` is already the signer when sending transactions.

```suggestion
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/files/client.ts.raw
> +// Just type run in the console on the bottom
`test` command is used to run the tests instead of `run` command.

```suggestion
// Just type `test` in the console on the bottom
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +```js
We can specify `bash` here instead of `js`.

```suggestion
```sh
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +```js
Incorrect language.

```suggestion
```rs
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +```js
Incorrect language.

```suggestion
```rs
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +Program:
Could you separate the `Program` and `Ts` parts into their own code blocks? Currently there is no syntax highlighting but there will be in the future.

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +```js
Incorrect language.

```suggestion
```rs
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +```js
Incorrect language.

```suggestion
```rs
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +```js
Incorrect language.

```suggestion
```rs
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +
Extra line.

```suggestion
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +    pub fn set_data(ctx: Context<SetData>, string_to_set: String, index: u64) -> Result<()> {
All of the following code has extra indentation.

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +}
Extra `}`

```suggestion
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/src/tutorials/tutorials.ts
> +  {
```suggestion

  {
```

2023-04-16 10:19 UTC, acheroncrypto commented on client/zeroCopy.jpg
Seems like a duplicate file. Please remove.

2023-04-16 11:13 UTC, Woody4618 commented on client/src/tutorials/Lumberjack/files/client.ts.raw
You mean so that people need to copy it over from the markdown? Do you think that would be a better learning experience? I thought its nice if people could just start the tutorial and run it and then play around with it. Not sure whats better

2023-04-16 11:47 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/files/client.ts.raw
Yes, I think it's better for people to follow the guide and write/copy the text themselves. It also reduces the duplicate code that we need to keep in sync in both places.

2023-04-16 15:02 UTC, Woody4618 commented on client/src/tutorials/Lumberjack/files/client.ts.raw
Ok, yeah i agree on the duplicate code. Ill rewrite it :)

2023-04-21 12:17 UTC, Woody4618 commented
Hey, I hope i didnt miss anything. Thanks for reviewing :)

2023-04-22 07:37 UTC, acheroncrypto requested changes
There has been a lot of formatting issues with the Rust code, fyi there is rustfmt available on playground and it does a reasonable job at formatting these. If a code errors, good chance there is an error with the code. For example:

This will error(both format and compile error):
```rs
#[repr(C)];
pub struct MyStruct {}
```

And this will format and compile fine:

```rs
#[repr(C)]
pub struct MyStruct {}
```

Sorry for back and forth requests but we just wouldn't want a user copying the code and running into errors.

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/TinyAdventureTwo/pages/3.md
> +...
This will break syntax parsing, better to comment out invalid code.

```suggestion
// ...
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/TinyAdventureTwo/pages/3.md
> +      return err!(MyError::WrongPassword);
Not formatted.

```suggestion
    return err!(MyError::WrongPassword);
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +        #[account(address = system_program::ID)]
Specifying the type `Program<'info, System>` already does this check, so checking again is redundant.

```suggestion
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +#[account(zero_copy)];
`;` after `#[account]` macro is invalid.

```suggestion
#[account(zero_copy)]
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +#[repr(C)];
`;` after this macro is invalid.

```suggestion
#[repr(C)]
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +or;
Better to comment out invalid Rust code.

```suggestion
// or
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +#[repr(packed)];
`;` after this macro is invalid.

```suggestion
#[repr(packed)]
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +    #[account(address = system_program::ID)]
Specifying the type `Program<'info, System>` already does this check, so checking again is redundant.

```suggestion
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +    #[account(address = system_program::ID)]
Specifying the type `Program<'info, System>` already does this check, so checking again is redundant.

```suggestion
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/pages/2.md
> +        seeds = [b"player".as_ref(), signer.key().as_ref()],
`b"player"` is already type `&[u8]`, adding another `.as_ref()` is redundant.

```suggestion
        seeds = [b"player", signer.key().as_ref()],
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/Lumberjack/pages/2.md
> +        seeds = [b"player".as_ref(), signer.key().as_ref()],
`b"player"` is already type `&[u8]`, adding another `.as_ref()` is redundant.

```suggestion
        seeds = [b"player", signer.key().as_ref()],
```

2023-04-22 07:37 UTC, acheroncrypto commented on client/src/tutorials/ZeroCopy/pages/1.md
> +
Could you format this code too? It's extra indented and starts with an extra line.

2023-04-24 07:07 UTC, merged