Tictactoe tutorial (edits made)
solana-playground/solana-playground pull request #201
Opened 2024-02-14 09:37 UTC by lostintime101

Put in a new PR as Github wasn't playing nicely.
All suggested changes have been made except for keeping 

  const player1 = pg.wallet.publicKey;
  const player2 = pg.wallet.publicKey;

feel it's easier just to keep it this way

2024-02-15 06:59 UTC, acheroncrypto reviewed
Thanks but did you try this locally to see if it works as expected?

2024-02-15 06:59 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/files/index.test.ts.raw
> +    printgame(game_account.grid);
```suggestion
    printgame(gameAccount.grid);
```

2024-02-15 06:59 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/files/index.test.ts.raw
> +    printgame(game_account.grid);
```suggestion
    printgame(gameAccount.grid);
```

2024-02-15 09:18 UTC, lostintime101 commented
I can just about get it to run locally.
Works as intended now except the for the thumbnail images.

![running](https://github.com/solana-playground/solana-playground/assets/92709487/7466bd40-8f52-4871-ac9e-20e9dd0abc46)

Quite painful, it keeps crashing (see error pic). I can't test build/deploy on local version, but I have built and tested the program previously on production.
![error](https://github.com/solana-playground/solana-playground/assets/92709487/7013354f-7055-42d5-b6ec-eece6745d59b)

2024-02-16 01:28 UTC, acheroncrypto reviewed
You need about 4 GB of memory to run it in development mode. Could you watch over your RAM usage to see if you're running out of memory?

I initially asked whether you tested it because I've seen a couple of errors like the file name being named `src/lib.rs` instead of `src/tictactoe.py` but those seem to be fixed now, thanks.

2024-02-16 01:28 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/pages/1.md
> +Okay, so let's start with how to represent the game state. We do this in Seahorse with an account class which we'll call "Game". This will need to store the grid, the players, who's turn it is and if
Can we use backticks instead of quotes when referencing code? For example, `Game` instead of "Game", and `u8` instead of 'u8'...

2024-02-16 01:28 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/pages/1.md
> +  grid: Array[u8,9]  # array of ints, length 9
```suggestion
  grid: Array[u8, 9]  # array of uints, length 9
```

2024-02-16 01:28 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/pages/1.md
> +  players: Array[Pubkey,2]  # array of 2 pubkeys
```suggestion
  players: Array[Pubkey, 2]  # array of 2 pubkeys
```

2024-02-16 01:28 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/pages/3.md
> +def play_game(player:Signer, game_data:Game, played_by:u8, move_position:u8):
```suggestion
def play_game(player: Signer, game_data: Game, played_by: u8, move_position: u8):
```

2024-02-16 03:28 UTC, lostintime101 commented
Okay, i think we're good.

Very likely a memory issue. Have uninstalled local Docker for now, should help

2024-02-17 04:31 UTC, acheroncrypto reviewed
Merged the tutorial assets (https://github.com/solana-playground/assets/pull/2), please run `git submodule update --remote` in this branch and commit the submodule changes.

2024-02-17 04:31 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/pages/3.md
> +Next we move to our game logic. Firstly we decrement the move_position by one so it fits the zero indexing of the array. Then we mark the grid with the player's number. Next we check if the player ha
```suggestion
Next we move to our game logic. Firstly we decrement the `move_position` by one so it fits the zero indexing of the array. Then we mark the grid with the player's number. Next we check if the player has won. This logic will be separated out into a separate function `win_check` which we'll come to next. We also switch the current player. Lastly we print the status of the game based on the result of the `win_check` function.
```

2024-02-17 04:31 UTC, acheroncrypto commented on client/src/tutorials/TictactoeSeahorse/files/index.test.ts.raw
> +  const systemProgram = anchor.web3.SystemProgram;
Doesn't seem to be used anywhere
```suggestion
```

2024-02-18 03:07 UTC, acheroncrypto requested changes
Thanks, looking great but [CI](https://github.com/solana-playground/solana-playground/actions/runs/7939653291/job/21693566539?pr=201) has code formatting errors:

```
$ prettier --check src/
Checking formatting...
[warn] src/tutorials/TictactoeSeahorse/pages/1.md
[warn] src/tutorials/TictactoeSeahorse/pages/3.md
[warn] src/tutorials/TictactoeSeahorse/pages/4.md
[warn] src/tutorials/tutorials.ts
[warn] Code style issues found in 4 files. Forgot to run Prettier?
```

You can fix this by running `yarn format`.

2024-02-18 18:06 UTC, acheroncrypto approved these changes
Thank you! This will most likely go live at the end of the month.

2024-02-18 18:07 UTC, merged